app/views/public_views.py
from flask import Blueprint, render_template
from flask import redirect, request, render_template, url_for
from flask_security import login_required, current_user
from bson.json_util import dumps
from flask_socketio import SocketIO
from db import *
public_blueprint = Blueprint('public', __name__, template_folder='templates', url_prefix="/user")
socketio = SocketIO()

@public_blueprint.route('/')
def home_page():
    rooms = get_rooms_for_user(current_user.username)
    return render_template('public/home_page.html',rooms=rooms)

@public_blueprint.route('/test')
def test_page():
    if current_user.is_authenticated:
        rooms = get_rooms_for_user(current_user.username)
    return render_template('public/test.html', rooms=rooms)

@public_blueprint.route('/create-room/', methods=['GET', 'POST'])
@login_required
def create_room():
    message = ''
    if request.method == 'POST':
        room_name = request.form.get('room_name')
        usernames = [username.strip() for username in request.form.get('members').split(',')]

        if len(room_name) and len(usernames):
            room_id = save_room(room_name, current_user.username)
            if current_user.username in usernames:
                usernames.remove(current_user.username)
            add_room_members(room_id, room_name, usernames, current_user.username)
            return redirect(url_for('view_room', room_id=room_id))
        else:
            message = "Failed to create room"
    return render_template('chat/create_room.html', message=message)


@public_blueprint.route('/rooms/<room_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_room(room_id):
    room = get_room(room_id)
    if room and is_room_admin(room_id, current_user.username):
        existing_room_members = [member['_id']['username'] for member in get_room_members(room_id)]
        room_members_str = ",".join(existing_room_members)
        message = ''
        if request.method == 'POST':
            room_name = request.form.get('room_name')
            room['name'] = room_name
            update_room(room_id, room_name)

            new_members = [username.strip() for username in request.form.get('members').split(',')]
            members_to_add = list(set(new_members) - set(existing_room_members))
            members_to_remove = list(set(existing_room_members) - set(new_members))
            if len(members_to_add):
                add_room_members(room_id, room_name, members_to_add, current_user.username)
            if len(members_to_remove):
                remove_room_members(room_id, members_to_remove)
            message = 'Room edited successfully'
            room_members_str = ",".join(new_members)
        return render_template('chat/edit_room.html', room=room, room_members_str=room_members_str, message=message)
    else:
        return "Room not found", 404


@public_blueprint.route('/rooms/<room_id>/')
@login_required
def view_room(room_id):
    room = get_room(room_id)
    rooms = get_rooms_for_user(current_user.username)
    if room and is_room_member(room_id, current_user.username):
        room_members = get_room_members(room_id)
        messages = get_messages(room_id)
        return render_template('public/view_room.html',rooms=rooms, username=current_user.username, room=room, room_members=room_members,
                               messages=messages)
    else:
        return "Room not found", 404


@public_blueprint.route('/rooms/<room_id>/messages/')
@login_required
def get_older_messages(room_id):
    room = get_room(room_id)
    if room and is_room_member(room_id, current_user.username):
        page = int(request.args.get('page', 0))
        messages = get_messages(room_id, page)
        return dumps(messages)
    else:
        return "Room not found", 404

app/views/success.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask.helpers import flash
from flask_security import login_required, current_user
from app import babel
from flask import current_app as app
import gettext

members_blueprint = Blueprint('members', __name__, template_folder='templates')

'''
@babel.localeselector
def get_locale():
    translations = [str(translation) for translation in
                    babel.list_translations()]
    return request.accept_languages.best_match(translations)


def set_lang(lang):
    i18n_dir = app.config['BABEL_TRANSLATION_DIRECTORIES']
    gettext.install('lang', i18n_dir)
    trans_file = i18n_dir + lang + '/LC_MESSAGES/flask_security'
    tr = gettext.translation(trans_file, 'locale',  languages=[lang])
    tr.install(True)
    app.jinja_env.install_gettext_translations(tr)
'''

@members_blueprint.before_app_first_request
def init_my_blueprint():
    if not app.user_datastore.get_user('user@example.com'):
        app.user_datastore.create_user(email='user@example.com',
                                       password='Password1')
    if not app.user_datastore.get_user('admin@example.com'):
        app.user_datastore.create_role(name="admin")
        app.user_datastore.create_user(email='admin@example.com',
                                       password='Password1', roles=['admin'])


@members_blueprint.before_app_request
def before_request():
    '''
    lang = get_locale()
    lang = lang if lang else app.config['BABEL_DEFAULT_LOCALE']
    set_lang(lang)
    '''
    if request.path.startswith('/admin') or request.path.startswith('/mod') or request.path.startswith('/biz') or request.path.startswith('/user'):
        if not current_user.is_authenticated:
            flash("You are not authorized", "error")
            return redirect(url_for('security.login'))

@members_blueprint.route('/success')
@login_required
def member_page():
    if current_user.is_authenticated:
        if current_user.has_role("admin"):
            return redirect('/admin')
        elif current_user.has_role("moderator"):
            return redirect('/mod')
        elif current_user.has_role("biz"):
            return redirect('/biz')
        else:
            return redirect('/user')
    else:
        return redirect(url_for('security.login'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block style %}
    {% endblock %}
    
    {% block head %}{% endblock %}

</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

app/templates/layout.html
{% extends "base.html" %}
{% block style %}
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <link href="/static/css/global.css" rel="stylesheet">
{% endblock %}
{% block head %}
<title>Test</title>
{% endblock %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{{ url_for('public.home_page') }}"><span class="glyphicon glyphicon-leaf text-success" aria-hidden="true"></span> {{ config.get('APP_NAME')  }}</a>
    </div>
    <div class="collapse navbar-collapse">
      <!-- <ul class="nav navbar-nav">
        <li class="nav-item"><a href="{{ url_for('public.home_page') }}" class="nav-link active">{{ _('Home Page') }}</a></li>
      </ul> -->
      <ul class="nav navbar-nav" style="margin-left: auto!important;">
        {% if current_user.is_authenticated %}
          <li class="nav-item"><a href="{{ url_for('members.member_page') }}" class="nav-link active"><span class="glyphicon glyphicon-user"></span> {{ _('Profile') }}</a></li>
          <li class="nav-item"><a href="{{ url_for('security.logout') }}" class="nav-link active">{{ _('Logout') }}</a></li>
        {% else %}
          <li class="nav-item"><a href="{{ url_for('security.register') }}" class="nav-link active">{{ _('Register') }}</a></li>
          <li class="nav-item"><a href="{{ url_for('security.login') }}" class="nav-link active"><span class="glyphicon glyphicon-log-in"></span>  {{ _('Login') }}</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>
  {% block content %}{% endblock %}

{% endblock %}